/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-120653-g85e8e59001-20250811"
#endif /* AVUTIL_FFVERSION_H */
