using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Tools
{
    public class TextWallException : Exception
    {
        public TextWallException() 
            :base(@"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nulla pharetra diam sit amet. Sagittis orci a scelerisque purus semper eget duis at. Viverra orci sagittis eu volutpat. Imperdiet nulla malesuada pellentesque elit eget gravida cum sociis. Duis at consectetur lorem donec massa sapien faucibus. A condimentum vitae sapien pellentesque habitant morbi. Leo duis ut diam quam nulla porttitor massa id neque. Dui faucibus in ornare quam viverra orci sagittis. Turpis egestas integer eget aliquet nibh praesent tristique. Viverra accumsan in nisl nisi scelerisque eu ultrices vitae. Nec nam aliquam sem et tortor consequat id. Orci porta non pulvinar neque laoreet suspendisse interdum. Mus mauris vitae ultricies leo integer malesuada nunc vel risus. Non diam phasellus vestibulum lorem. Non consectetur a erat nam at lectus urna. Ullamcorper velit sed ullamcorper morbi tincidunt ornare.

Amet venenatis urna cursus eget nunc scelerisque viverra mauris. Adipiscing elit ut aliquam purus sit amet luctus venenatis. Ut tortor pretium viverra suspendisse potenti nullam ac tortor. Lacus viverra vitae congue eu consequat ac. Posuere lorem ipsum dolor sit amet consectetur. Dolor sit amet consectetur adipiscing elit. Lorem dolor sed viverra ipsum nunc aliquet bibendum enim facilisis. Neque gravida in fermentum et. Pretium aenean pharetra magna ac placerat vestibulum. Sodales neque sodales ut etiam sit amet nisl purus in. Volutpat diam ut venenatis tellus in metus vulputate eu scelerisque. Justo laoreet sit amet cursus sit. Duis ut diam quam nulla. Ut ornare lectus sit amet est placerat in egestas erat. Sit amet nulla facilisi morbi. Amet mauris commodo quis imperdiet massa tincidunt. Mi quis hendrerit dolor magna eget.

In ornare quam viverra orci sagittis eu volutpat odio facilisis. Sed blandit libero volutpat sed cras ornare arcu dui. Imperdiet massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Ullamcorper dignissim cras tincidunt lobortis. Ultricies mi quis hendrerit dolor magna eget est lorem. Mi in nulla posuere sollicitudin aliquam. Sagittis id consectetur purus ut faucibus pulvinar elementum integer enim. Nisl vel pretium lectus quam id leo in vitae turpis. Amet est placerat in egestas erat imperdiet sed euismod. Adipiscing vitae proin sagittis nisl rhoncus mattis. Sit amet risus nullam eget felis. Sed nisi lacus sed viverra tellus. Convallis convallis tellus id interdum. Consequat nisl vel pretium lectus quam id leo. Quam id leo in vitae turpis massa. Est sit amet facilisis magna etiam tempor orci eu. Risus in hendrerit gravida rutrum quisque non tellus orci ac.

Arcu vitae elementum curabitur vitae nunc. At risus viverra adipiscing at in tellus integer feugiat. Sodales ut eu sem integer. Cursus in hac habitasse platea dictumst. Quam elementum pulvinar etiam non. Donec adipiscing tristique risus nec feugiat in fermentum. Sed sed risus pretium quam vulputate dignissim suspendisse in. Nulla pellentesque dignissim enim sit amet venenatis. Nullam eget felis eget nunc. Maecenas sed enim ut sem viverra aliquet eget. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt.

Maecenas ultricies mi eget mauris pharetra et ultrices neque ornare. Risus sed vulputate odio ut enim blandit volutpat maecenas volutpat. Ipsum dolor sit amet consectetur adipiscing elit. Mattis rhoncus urna neque viverra justo nec. Ullamcorper malesuada proin libero nunc consequat. Potenti nullam ac tortor vitae purus faucibus ornare suspendisse sed. At ultrices mi tempus imperdiet nulla malesuada pellentesque elit. Nisi vitae suscipit tellus mauris a diam maecenas. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum. Mauris cursus mattis molestie a iaculis at erat pellentesque. Tincidunt lobortis feugiat vivamus at augue eget. Dignissim cras tincidunt lobortis feugiat vivamus at augue eget arcu. Neque sodales ut etiam sit amet nisl. Pulvinar sapien et ligula ullamcorper malesuada proin libero nunc consequat. Bibendum neque egestas congue quisque egestas. Ante metus dictum at tempor commodo ullamcorper a lacus. Nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper. Massa tincidunt dui ut ornare lectus sit amet est placerat.

Convallis convallis tellus id interdum velit laoreet. Urna neque viverra justo nec ultrices dui sapien. Nulla facilisi morbi tempus iaculis urna id volutpat. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi. Auctor neque vitae tempus quam pellentesque nec. Ut eu sem integer vitae justo. Aliquam purus sit amet luctus venenatis lectus magna fringilla. Magna fringilla urna porttitor rhoncus dolor purus non enim praesent. Commodo ullamcorper a lacus vestibulum sed arcu non odio. Amet commodo nulla facilisi nullam vehicula. Nunc congue nisi vitae suscipit tellus.

Eget velit aliquet sagittis id consectetur. Interdum consectetur libero id faucibus nisl. Tempus egestas sed sed risus pretium quam vulputate. Nisl rhoncus mattis rhoncus urna neque. Commodo nulla facilisi nullam vehicula ipsum a. Amet commodo nulla facilisi nullam. Suscipit tellus mauris a diam maecenas sed. Et molestie ac feugiat sed lectus. Nulla pharetra diam sit amet nisl suscipit. Facilisis sed odio morbi quis commodo. Nibh sit amet commodo nulla facilisi nullam vehicula ipsum. Potenti nullam ac tortor vitae. Tellus orci ac auctor augue mauris augue neque gravida in.

Maecenas volutpat blandit aliquam etiam erat velit scelerisque in dictum. Scelerisque varius morbi enim nunc faucibus. Ut etiam sit amet nisl. Feugiat in ante metus dictum at tempor. Sapien pellentesque habitant morbi tristique senectus. Pulvinar etiam non quam lacus suspendisse. Risus nullam eget felis eget nunc. Metus dictum at tempor commodo ullamcorper. Non diam phasellus vestibulum lorem sed risus ultricies. Aliquet bibendum enim facilisis gravida neque convallis a. Velit ut tortor pretium viverra suspendisse potenti nullam ac tortor. Amet est placerat in egestas erat imperdiet sed euismod nisi. Elementum pulvinar etiam non quam lacus. Vitae justo eget magna fermentum. At varius vel pharetra vel turpis nunc eget lorem. Id diam maecenas ultricies mi. Pretium aenean pharetra magna ac placerat vestibulum. Sagittis aliquam malesuada bibendum arcu vitae elementum curabitur.

Sit amet consectetur adipiscing elit ut aliquam. Eget lorem dolor sed viverra ipsum nunc aliquet. Ultrices in iaculis nunc sed augue. Justo eget magna fermentum iaculis eu. Convallis aenean et tortor at risus viverra adipiscing at in. Urna nec tincidunt praesent semper. Imperdiet proin fermentum leo vel. Neque gravida in fermentum et sollicitudin ac. Amet nulla facilisi morbi tempus. Neque laoreet suspendisse interdum consectetur libero. Eu nisl nunc mi ipsum. Varius quam quisque id diam vel. Pulvinar elementum integer enim neque.

Interdum velit laoreet id donec ultrices tincidunt arcu. Pharetra et ultrices neque ornare aenean euismod elementum nisi quis. Nullam eget felis eget nunc lobortis mattis aliquam faucibus purus. Faucibus et molestie ac feugiat sed lectus vestibulum. Lorem dolor sed viverra ipsum nunc aliquet bibendum enim. Elementum nibh tellus molestie nunc. Posuere lorem ipsum dolor sit. Et tortor at risus viverra adipiscing at in tellus integer. Eget nunc scelerisque viverra mauris in aliquam sem fringilla. Gravida neque convallis a cras semper auctor neque vitae tempus. Sit amet nisl purus in mollis nunc sed id. Varius duis at consectetur lorem donec massa. Maecenas volutpat blandit aliquam etiam erat velit scelerisque.

Maecenas sed enim ut sem viverra aliquet. Adipiscing bibendum est ultricies integer quis auctor. Magna sit amet purus gravida quis blandit turpis cursus. Pellentesque massa placerat duis ultricies lacus. Ut eu sem integer vitae justo. Est ullamcorper eget nulla facilisi etiam. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Maecenas accumsan lacus vel facilisis volutpat est velit. Ultrices sagittis orci a scelerisque purus semper eget duis at. Egestas congue quisque egestas diam. Morbi blandit cursus risus at. Amet mauris commodo quis imperdiet massa. Ullamcorper sit amet risus nullam eget felis eget nunc. Curabitur vitae nunc sed velit dignissim sodales ut eu. Euismod nisi porta lorem mollis aliquam. Faucibus a pellentesque sit amet porttitor eget dolor morbi non. Facilisis gravida neque convallis a cras semper auctor. Sit amet justo donec enim diam vulputate ut pharetra. Neque sodales ut etiam sit amet nisl purus in mollis.

Enim nec dui nunc mattis enim ut. Turpis egestas pretium aenean pharetra magna ac. Nulla facilisi cras fermentum odio. Viverra nam libero justo laoreet sit amet cursus sit amet. Amet mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Urna molestie at elementum eu facilisis. Consectetur libero id faucibus nisl. Amet purus gravida quis blandit turpis cursus in hac. In vitae turpis massa sed. Dui faucibus in ornare quam viverra orci. Posuere lorem ipsum dolor sit amet consectetur adipiscing elit.

Faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis. Senectus et netus et malesuada fames ac turpis egestas. Rhoncus urna neque viverra justo. Scelerisque felis imperdiet proin fermentum leo vel orci porta. Adipiscing at in tellus integer feugiat scelerisque varius. Duis ut diam quam nulla porttitor massa id neque. Proin nibh nisl condimentum id venenatis a condimentum vitae sapien. Sagittis id consectetur purus ut faucibus. Faucibus interdum posuere lorem ipsum dolor sit amet. Proin nibh nisl condimentum id venenatis a condimentum vitae. Scelerisque eu ultrices vitae auctor eu augue. Ante metus dictum at tempor commodo ullamcorper a lacus vestibulum. Morbi tincidunt augue interdum velit euismod in pellentesque.

Vulputate mi sit amet mauris commodo. Scelerisque varius morbi enim nunc faucibus. Scelerisque viverra mauris in aliquam sem fringilla ut. In fermentum et sollicitudin ac orci phasellus egestas. Sit amet purus gravida quis blandit turpis. Accumsan lacus vel facilisis volutpat. Blandit turpis cursus in hac. Sed blandit libero volutpat sed cras ornare arcu. Amet aliquam id diam maecenas ultricies. Fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. Mi eget mauris pharetra et ultrices neque ornare. Enim facilisis gravida neque convallis a cras semper auctor. Tristique senectus et netus et malesuada fames ac turpis. Ornare lectus sit amet est. Tempor nec feugiat nisl pretium. Vitae sapien pellentesque habitant morbi tristique senectus et. Risus quis varius quam quisque id diam vel quam elementum. Eu tincidunt tortor aliquam nulla facilisi cras fermentum odio. Duis at consectetur lorem donec massa sapien.

Sed augue lacus viverra vitae. Sociis natoque penatibus et magnis dis parturient montes. Ut lectus arcu bibendum at varius vel. Iaculis eu non diam phasellus vestibulum lorem sed. Ullamcorper morbi tincidunt ornare massa eget egestas purus. A lacus vestibulum sed arcu. Eu facilisis sed odio morbi quis commodo odio. Posuere ac ut consequat semper viverra nam libero justo laoreet. Aliquam etiam erat velit scelerisque in. Ac turpis egestas sed tempus. At tellus at urna condimentum mattis pellentesque. Ultrices neque ornare aenean euismod elementum nisi quis eleifend quam. Malesuada fames ac turpis egestas maecenas pharetra convallis posuere morbi. Adipiscing at in tellus integer feugiat.

Libero volutpat sed cras ornare arcu dui vivamus arcu. Est ultricies integer quis auctor elit sed vulputate. Feugiat pretium nibh ipsum consequat nisl vel pretium lectus. Euismod nisi porta lorem mollis aliquam ut porttitor leo a. Tellus molestie nunc non blandit massa enim nec dui. Ac feugiat sed lectus vestibulum. Viverra mauris in aliquam sem fringilla ut morbi tincidunt. Sed enim ut sem viverra aliquet eget. Mi proin sed libero enim sed faucibus. Habitasse platea dictumst vestibulum rhoncus. Vivamus arcu felis bibendum ut tristique et egestas quis. Bibendum neque egestas congue quisque egestas diam in arcu. Orci nulla pellentesque dignissim enim sit amet venenatis urna cursus. Commodo sed egestas egestas fringilla phasellus faucibus scelerisque. Ut lectus arcu bibendum at varius vel. Mauris commodo quis imperdiet massa. Odio euismod lacinia at quis risus. Adipiscing bibendum est ultricies integer quis auctor elit sed vulputate. Ullamcorper eget nulla facilisi etiam dignissim diam quis enim. Malesuada pellentesque elit eget gravida cum.

Quis blandit turpis cursus in hac. Sit amet volutpat consequat mauris nunc congue nisi. Et netus et malesuada fames ac. Leo integer malesuada nunc vel risus commodo. Dignissim convallis aenean et tortor at risus viverra adipiscing at. In fermentum posuere urna nec tincidunt praesent. Id eu nisl nunc mi. Purus gravida quis blandit turpis cursus in hac habitasse. Risus sed vulputate odio ut enim blandit volutpat maecenas. Fringilla est ullamcorper eget nulla facilisi etiam. Tellus mauris a diam maecenas sed enim ut. Id nibh tortor id aliquet lectus proin. Id donec ultrices tincidunt arcu non sodales.

Id leo in vitae turpis. Neque aliquam vestibulum morbi blandit cursus risus. Tellus elementum sagittis vitae et leo duis ut diam. At volutpat diam ut venenatis tellus. Dolor sit amet consectetur adipiscing elit ut. Id neque aliquam vestibulum morbi blandit cursus risus at. Nam libero justo laoreet sit amet cursus sit. Sit amet dictum sit amet justo donec enim diam. Diam vel quam elementum pulvinar etiam non quam lacus. Et netus et malesuada fames ac. Sit amet cursus sit amet dictum sit amet justo. Enim sit amet venenatis urna. Amet facilisis magna etiam tempor orci eu.

Nulla pharetra diam sit amet nisl suscipit. Fermentum iaculis eu non diam phasellus vestibulum lorem. Dolor sed viverra ipsum nunc aliquet bibendum enim facilisis gravida. Metus vulputate eu scelerisque felis imperdiet proin fermentum. Rutrum quisque non tellus orci ac. Arcu felis bibendum ut tristique et egestas quis ipsum suspendisse. Bibendum ut tristique et egestas quis. Nibh tortor id aliquet lectus proin nibh nisl condimentum. Erat imperdiet sed euismod nisi porta lorem mollis. Pulvinar mattis nunc sed blandit libero volutpat sed cras. Et tortor at risus viverra.

Pellentesque sit amet porttitor eget dolor morbi non arcu risus. Nibh venenatis cras sed felis eget velit aliquet. Nibh praesent tristique magna sit amet. Justo eget magna fermentum iaculis. Condimentum lacinia quis vel eros donec ac odio. Nisi porta lorem mollis aliquam ut porttitor leo a. Mi sit amet mauris commodo quis imperdiet massa tincidunt nunc. Ullamcorper morbi tincidunt ornare massa eget egestas. Enim facilisis gravida neque convallis a cras. Vel turpis nunc eget lorem dolor. Fermentum posuere urna nec tincidunt praesent semper feugiat.")
        {
        }
    }
}
